### PR TITLE
Allow to configure cache version

### PR DESCRIPTION
**Pull request by mickel8**

### CODE REVIEW

**Review by bblaszkow06 — APPROVED** [review]

**Comment by bblaszkow06** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/membraneframework/elixir?version=dev:e447ed6929d1b768701183033d4699b29bfb0ee1

**Comment by bblaszkow06** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/membraneframework/elixir?version=dev:6218c369cf05208a534f6f08644c4ea097bd029c

**Comment by mickel8** [comment]
I checked this here https://github.com/membraneframework/membrane_videoroom/pull/134 and it seems to work. I also added an example with cache reset so you might to take a look once again

**Review by bblaszkow06 — APPROVED** [review]

**Comment by bblaszkow06** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/membraneframework/elixir?version=dev:6cf4b98adb42fb69b172c9e4fe56dcd6e6c63729

**Comment by bblaszkow06** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/membraneframework/elixir?version=1.3.0

**Pull request merged**
