### PR TITLE
Remove all deps before installing

### PR DESCRIPTION
**Pull request by Noarkhh**

### CODE REVIEW

**Comment by bblaszkow06** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/membraneframework/elixir?version=dev:5a491ec3e573ab2d10e4445cbb744fa996359f7e

**Comment by bblaszkow06** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/membraneframework/elixir?version=dev:a5ec1c4a36b680bd50813b37cf4a53b9bfb5680c

**Comment by bblaszkow06** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/membraneframework/elixir?version=dev:b3a7e75c7d28808fa5964fc74d01f3a3f31e70e7

**Review by mat-hek — APPROVED** [review]

**Comment by bblaszkow06** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/membraneframework/elixir?version=dev:f0b42b2d8a82c0150e3a9fcdd401364121c22a4b

**Comment by bblaszkow06** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/membraneframework/elixir?version=dev:f0b42b2d8a82c0150e3a9fcdd401364121c22a4b

**Comment by bblaszkow06** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/membraneframework/elixir?version=1.4.2

**Pull request merged**
